version: "3.9"
services:
  logstash:
    image: logstash:8.10.2
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5044:5044/udp"
    volumes:
      - ./elk-deploy/logstash.conf:/config/logstash.conf:ro
      - ./elk-deploy/nginx:/etc/logstash/patterns/nginx
    command: logstash -f /config/logstash.conf
    networks:
      - my_network

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - my_network

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - my_network

networks:
  my_network:
    external: True