@startuml
!theme materia

title  АРХИТЕКТУРА ТO BE

agent Админ
agent Клиент
agent Аналитик

node "Admin service" as admin_service {
    component "Admin panel" as django
    database "Movies relational DB" as movies_db
    django <--> movies_db
}

node "Auth service" as auth_service {
    component "Auth API" as auth_api
    database "Auth relational DB" as auth_db
    database "Auth cache storage" as cache_storage
    auth_api <--> auth_db
    auth_api <--> cache_storage
}

node "Film service" as film_service {
    component "Film API" as film_api
    database "Film search DB" as film_db
    database "Film cache storage"  as cache_storage_film
    film_api <--> film_db
    film_api <--> cache_storage_film
}

component "ETL" as etl_films
    movies_db <-- etl_films
    etl_films --> film_db

node "UGC service" as  ugc_service {
    component "UGC API" as ugc_api
    database "Message broker" as msg_broker
    component "ETL" as ugc_etl
    database "OLAP DB" as olap_db
    ugc_api --> msg_broker:  "Отправка событий"
    msg_broker <-- ugc_etl:  "PULL событий"
    ugc_etl --> olap_db:  "Загрузка событий"
}

Админ --> django: CRUD контента
Админ --> auth_api: Создание роли для пользователя
Клиент --> auth_api:  Авторизация, Pегистрация
Клиент --> film_api:  Запрос контента
Клиент --> ugc_api:  Аналитические запросы пользователя
Аналитик --> olap_db: Аналитические данные
@enduml