version: "3.9"

services:
  bench-pg:
    image: postgres:15
    env_file:
    - .env
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped 

  benchmark:
    build: ./benchmark
    env_file:
      - .env
    depends_on:
      - bench-pg

volumes:
  pg_data: