name: Python application

on:
  push:
    branches: [ feature/git-actions ]
  pull_request:
    branches: [ feature/git-actions ]
    
jobs:
  ugc-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Build the stack
      run: docker-compose -f docker-compose-actions.yml up -d --build
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/functional/requirements.txt
        pip install yamllint flake8-github-annotations


    - name: Wait kafka
      run: |
        python tests/functional/utils/wait_for_kafka.py

    - name: Test with pytest
      run: |
        pytest tests/functional/

    - name: Lint report
      run: |
        flake8 ugc_api/src/ --count --select=E9,F63,F7,F82 --show-source --statistics --format github
        flake8 ugc_api/src/ --count --exit-zero --format github

    - name: Check mypy
      run: |
        mypy ugc_api/

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}
          
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

